### ISSUE TITLE
Difficulties with adding teacher to subject on teacher profile

### ISSUE THREAD

**Issue by mateuszlichon** [CodersLabAlumni/SchoolManager#1]
After trying to add new subject an **error occurs**.
Error message: Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: org.hibernate.PropertyAccessException: Null value was assigned to a property [class pl.schoolmanager.entity.Teacher.id] of primitive type setter of pl.schoolmanager.entity.Teacher.id; nested exception is javax.persistence.PersistenceException: org.hibernate.PropertyAccessException: Null value was assigned to a property [class pl.schoolmanager.entity.Teacher.id] of primitive type setter of pl.schoolmanager.entity.Teacher.id

**Comment by Lukasz-Bdn** [comment]
Fajny problem!

**Comment by mateuszlichon** [comment]
I'll try to solve it using converter.
