### ISSUE TITLE
Creating new message gives HTTP Status 500

### ISSUE THREAD

**Issue by PietrygaM** [CodersLabAlumni/SchoolManager#11]
HTTP Status 500 - Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.GenericJDBCException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement

**Comment by przemyslawkonik** [comment]
It works fine for me, no errors given.
